blank_issues_enabled: true
contact_links:
  - name: E-mail
    url: mailto:sonothing.emailme@gmail.com?subject=%5Bbigrat.monster%5D%20Issue
    about: If you prefer to use e-mails, please click this link.
